//! Assert the Rust crypto matches the Python reference byte-for-byte.
//!
//! Vectors are generated by `tools/gen_vectors.py` into `tests/vectors.json`.

use barely_ap::crypto;
use barely_ap::util::{from_hex, to_hex};
use serde_json::Value;

fn vectors() -> Value {
    let raw = include_str!("vectors.json");
    serde_json::from_str(raw).expect("vectors.json parses")
}

fn hexf(v: &Value, key: &str) -> Vec<u8> {
    from_hex(
        v[key]
            .as_str()
            .unwrap_or_else(|| panic!("missing key {key}")),
    )
}

#[test]
fn pbkdf2_pmk_matches() {
    let c = &vectors()["crypto"];
    let psk = c["psk"].as_str().unwrap();
    let ssid = c["ssid"].as_str().unwrap();
    let pmk = crypto::pbkdf2_pmk(psk, ssid);
    assert_eq!(to_hex(&pmk), c["pmk"].as_str().unwrap());
}

#[test]
fn prf512_ptk_matches() {
    let c = &vectors()["crypto"];
    let ptk = crypto::custom_prf512(
        &hexf(c, "pmk"),
        &hexf(c, "amac"),
        &hexf(c, "smac"),
        &hexf(c, "anonce"),
        &hexf(c, "snonce"),
    );
    assert_eq!(to_hex(&ptk), c["ptk"].as_str().unwrap());
    assert_eq!(to_hex(&ptk[..16]), c["kck"].as_str().unwrap());
    assert_eq!(to_hex(&ptk[16..32]), c["kek"].as_str().unwrap());
    assert_eq!(to_hex(&ptk[32..48]), c["tk"].as_str().unwrap());
}

#[test]
fn ccmp_encrypt_matches() {
    let c = &vectors()["crypto"];
    let key = hexf(c, "ccm_key");
    let nonce: [u8; 13] = hexf(c, "ccm_nonce").try_into().unwrap();
    let aad = hexf(c, "ccm_aad");
    let plain = hexf(c, "ccm_plain");
    let (cipher, tag) = crypto::run_ccmp_encrypt(&key, &nonce, &aad, &plain);
    assert_eq!(to_hex(&cipher), c["ccm_cipher"].as_str().unwrap());
    assert_eq!(to_hex(&tag), c["ccm_tag"].as_str().unwrap());
}

#[test]
fn ccmp_decrypt_roundtrips_and_validates() {
    let c = &vectors()["crypto"];
    let key = hexf(c, "ccm_key");
    let nonce: [u8; 13] = hexf(c, "ccm_nonce").try_into().unwrap();
    let aad = hexf(c, "ccm_aad");
    let cipher = hexf(c, "ccm_cipher");
    let tag = hexf(c, "ccm_tag");
    let (plain, valid) = crypto::run_ccmp_decrypt(&key, &nonce, &aad, &cipher, &tag);
    assert!(valid, "tag must verify");
    assert_eq!(to_hex(&plain), c["ccm_plain"].as_str().unwrap());

    // a corrupted tag must fail
    let mut bad = tag.clone();
    bad[0] ^= 0xff;
    let (_p, valid2) = crypto::run_ccmp_decrypt(&key, &nonce, &aad, &cipher, &bad);
    assert!(!valid2, "corrupted tag must not verify");
}

#[test]
fn ccmp_selftest_vector_matches() {
    let c = &vectors()["crypto"];
    let key = [b'k'; 16];
    let nonce = [b'n'; 13];
    let aad = [b'a'; 22];
    let plain = [b'P'; 128];
    let (cipher, tag) = crypto::run_ccmp_encrypt(&key, &nonce, &aad, &plain);
    assert_eq!(to_hex(&cipher), c["selftest_cipher"].as_str().unwrap());
    assert_eq!(to_hex(&tag), c["selftest_tag"].as_str().unwrap());
}

#[test]
fn aes_key_wrap_matches_and_unwraps() {
    let c = &vectors()["crypto"];
    let kek = hexf(c, "kek_for_wrap");
    let plain = hexf(c, "wrap_plain");
    let wrapped = crypto::aes_wrap(&kek, &plain);
    assert_eq!(to_hex(&wrapped), c["wrapped"].as_str().unwrap());

    let unwrapped = crypto::aes_unwrap(&kek, &wrapped).expect("unwrap succeeds");
    assert_eq!(to_hex(&unwrapped), c["wrap_plain"].as_str().unwrap());
}

#[test]
fn pad_key_data_matches() {
    let c = &vectors()["crypto"];
    assert_eq!(
        to_hex(&crypto::pad_key_data(vec![1, 2, 3, 4, 5])),
        c["pad_key_data_5"].as_str().unwrap()
    );
    assert_eq!(
        to_hex(&crypto::pad_key_data(vec![1, 2, 3, 4, 5, 6, 7, 8])),
        c["pad_key_data_8"].as_str().unwrap()
    );
}

#[test]
fn aes_cmac_rfc4493() {
    // RFC 4493 test vectors for AES-128-CMAC (used by BIP-CMAC-128).
    let k = from_hex("2b7e151628aed2a6abf7158809cf4f3c");
    let m = from_hex("6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710");

    assert_eq!(
        to_hex(&crypto::aes_cmac(&k, &[])),
        "bb1d6929e95937287fa37d129b756746"
    );
    assert_eq!(
        to_hex(&crypto::aes_cmac(&k, &m[..16])),
        "070a16b46b4d4144f79bdd9dd04a287c"
    );
    assert_eq!(
        to_hex(&crypto::aes_cmac(&k, &m[..40])),
        "dfa66747de9ae63030ca32611497c827"
    );
    assert_eq!(
        to_hex(&crypto::aes_cmac(&k, &m[..64])),
        "51f0bebf7e3b9d92fc49741779363cfe"
    );
}

#[test]
fn sha256_ptk_is_min_max_symmetric() {
    // The 802.11 PTK context uses Min/Max of the addresses and nonces, so the
    // derivation must be independent of argument order. (The sha256_prf itself
    // is anchored against IEEE J.10 via the SAE KCK/PMK in tests/sae_vectors.rs,
    // and the full SHA-256 4-way is cross-validated against the independent
    // Python implementation in tests/interop.rs.)
    let pmk = [0x11u8; 32];
    let a = [0xaau8; 6];
    let b = [0xbbu8; 6];
    let na = [0x01u8; 32];
    let nb = [0x02u8; 32];
    let p1 = crypto::derive_ptk_sha256(&pmk, &a, &b, &na, &nb);
    let p2 = crypto::derive_ptk_sha256(&pmk, &b, &a, &nb, &na);
    assert_eq!(p1, p2, "PTK must be symmetric in (addr,nonce) ordering");
    // and varies with the actual key material (sanity: not a constant)
    let nc = [0x03u8; 32];
    let p3 = crypto::derive_ptk_sha256(&pmk, &a, &b, &na, &nc);
    assert_ne!(p1, p3);
}

#[test]
fn hmac_sha1_matches() {
    let c = &vectors()["crypto"];
    let mac = crypto::hmac_sha1(&[b'k'; 16], b"hello world");
    assert_eq!(to_hex(&mac[..16]), c["hmac_sha1_demo"].as_str().unwrap());
}
