use crate::util::try_mac_to_bytes;
use zeroize::{Zeroize, Zeroizing};

/// One credential-file entry: `(MAC filter, passphrase)`, `None` MAC = wildcard.
pub type PskEntry = (Option<[u8; 6]>, String);

struct PskEntryGuard(Vec<PskEntry>);

impl Drop for PskEntryGuard {
    fn drop(&mut self) {
        for (_, password) in &mut self.0 {
            password.zeroize();
        }
    }
}

/// Parse either credential format generated by SPR:
///
/// - WPA: `MAC passphrase` (`00:00:00:00:00:00` is wildcard)
/// - SAE: `passphrase|mac=MAC` (`ff:ff:ff:ff:ff:ff` is wildcard)
///
/// Both wildcard spellings are accepted in either form and returned as `None`.
pub fn parse_psk_file(path: &str) -> Result<Vec<PskEntry>, String> {
    let text = Zeroizing::new(std::fs::read_to_string(path).map_err(|e| e.to_string())?);
    let mut out = PskEntryGuard(Vec::new());
    for (line_no, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (mac_tok, pass) = if line.contains("|mac=") {
            let mut fields = line.split('|');
            let pass = fields.next().unwrap_or("").trim();
            let mac = fields
                .find_map(|field| field.trim().strip_prefix("mac="))
                .ok_or_else(|| format!("line {}: SAE entry missing mac=", line_no + 1))?;
            (mac, pass)
        } else {
            match line.split_once(char::is_whitespace) {
                Some((mac, pass)) => (mac, pass.trim()),
                None => {
                    return Err(format!(
                        "line {}: expected 'MAC passphrase' or 'passphrase|mac=MAC'",
                        line_no + 1
                    ));
                }
            }
        };
        if pass.is_empty() {
            return Err(format!("line {}: empty passphrase", line_no + 1));
        }
        let mac = if mac_tok.eq_ignore_ascii_case("00:00:00:00:00:00")
            || mac_tok.eq_ignore_ascii_case("ff:ff:ff:ff:ff:ff")
        {
            None
        } else {
            Some(
                try_mac_to_bytes(mac_tok)
                    .ok_or_else(|| format!("line {}: invalid MAC {mac_tok:?}", line_no + 1))?,
            )
        };
        out.0.push((mac, pass.to_string()));
    }
    Ok(std::mem::take(&mut out.0))
}
