driver=nl80211
interface=wlan1
ctrl_interface=/tmp/hostap-client-ctrl
ssid=turtlenet
hw_mode=g
channel=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
ieee80211w=2
sae_pwe=2
sae_password=password1234
wpa_group_rekey=2
