# WPA2 reference AP profile
driver=nl80211
interface=wlan1
ctrl_interface=/tmp/reference-ap-client-ctrl
ssid=turtlenet
hw_mode=g
channel=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=password1234
wpa_group_rekey=2
